[package]
name = "spotui"
version = "0.1.0"
authors = ["Spanfile <spansdev@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
tokio = { version = "0.2.11", features = ["macros", "rt-threaded", "time", "stream", "blocking"] }
futures = "0.3.4"
termion = "1.5.5"
