[package]
authors = ["Spanfile <spansdev@gmail.com>"]
edition = "2018"
name = "spotui"
version = "0.1.0"

[dependencies]
anyhow = "1.0.26"
termion = "1.5.5"
tui = "0.8.0"

[dependencies.tokio]
features = ["macros", "rt-threaded", "time", "stream", "blocking"]
version = "0.2.11"
