[package]
name = "spotui"
version = "0.1.0"
authors = ["Spanfile <spansdev@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.26"
async-std = { version = "1.5.0", features = ["unstable"] }
futures = "0.3.4"
